version: "3.2"

services:

  revproxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${TURP_APP_DATA}/.revproxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf"
    environment:
      - DEFAULT_HOST=local.test
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    healthcheck:
      test: ["CMD", "exit", "0"]
    networks:
      - turple_network

  vscode_shawn:
    build: ./builds/vscode
    restart: always
    volumes:
      - "/mnt/turp/coder/shawn:/home/coder"
      - "${TURP_DATA_CODE}/code/shawn:/home/coder/project"
    ports:
      - 8080:8080

  vscode_leanne:
    build: ./builds/vscode
    restart: always
    volumes:
      - "/mnt/turp/coder/leanne:/home/coder"
      - "${TURP_DATA_CODE}/code/leanne:/home/coder/project"
    ports:
      - 8082:8080
      - 8083:8081

networks:
  turple_network:
    driver: bridge
