version: "3.2"

services:
  vscode_shawn:
    image: sturple/coder
    restart: always
    volumes:
      - "/mnt/turp/coder/shawn:/home/coder"
      - "${TURP_DATA_CODE}/code/shawn:/home/coder/project"
    ports:
      - 8080:8080

  vscode_brandon:
    image: sturple/coder
    restart: always
    volumes:
      - "/mnt/turp/coder/brandon:/home/coder"
      - "${TURP_DATA_CODE}/code/brandon:/home/coder/project"
    ports:
      - 8021:8080

  vscode_leanne:
    image: sturple/coder
    restart: always
    volumes:
      - "/mnt/turp/coder/leanne:/home/coder"
      - "${TURP_DATA_CODE}/code/leanne:/home/coder/project"
    ports:
      - 8082:8080
networks:
  turple_network:
    driver: bridge
